### ISSUE TITLE
Make MergedConfiguration.as_ns() work recursively

### ISSUE THREAD

**Issue by pjz** [pjz/mincfg#2]
Currently it only renders the top-level dict as a SimpleNamespace; it should recurse so that a yaml file like:

```
a:
  b:
    d: 1
    d2: 2
  c:
    d: 1
    d2: 2
```
will allow `assert cfg.a.b.d == cfg.a.c.d`
